export const sagaActions = {
    LOGIN: "LOGIN",
    REGISTER: "REGISTER",
    GET_USER: "GET_USER",
    ONBOARD_USER: "ONBOARD_USER",
    FETCH_WEIGHT_HISTORY: "FETCH_WEIGHT_HISTORY",
    ADD_WEIGHT: "ADD_WEIGHT",
};
  